### ISSUE TITLE
Nothing Major (README.md)

### ISSUE THREAD

**Issue by lemondev01** [CaptainGoatee/goated-discord-handler-demo#1]
I would recommend mentioning for new developers, if they done want button actions to work, etc. Within the index.js all the have to do is put a `//` Infront of the selected line and it will stop it from working.

Just thought I would suggest it :)

**Comment by TheJavachipDev** [comment]
> I would recommend mentioning for new developers, if they done want button actions to work, etc. Within the index.js all the have to do is put a `//` Infront of the selected line and it will stop it from working.
> 
> 
> 
> Just thought I would suggest it :)



They can use the deleted variable in the button file too
